apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasMigration
metadata:
  name: atlas-db-poc-migration
  annotations:
      argocd.argoproj.io/sync-wave: "0"
spec:
  credentials:
    scheme: postgres
    hostFrom:
      configMapKeyRef:
        name: postgresql-endpoint           
        key: dns_name 
    user: {{ .Values.db.user }}
    password: {{ .Values.db.pass }}
    database: {{ .Values.db.db }}
    portFrom:
      configMapKeyRef:
        name: postgresql-endpoint
        key: port
    parameters:
      sslmode: disable
  dir:
    configMapRef:
      name: "migration-dir" # ConfigMap name of atlas-migration-configmap.yaml