apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-dir
data:
{{- $files := .Files }}
  {{ range $path, $_ :=  $files.Glob  "migrations/*.sql" }}
  {{ trimPrefix "migrations/" $path }}: '{{ $files.Get $path }}'
  {{- end }}
  atlas.sum: '{{ $files.Get "migrations/atlas.sum" }}'