apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-dir
  annotations:
      argocd.argoproj.io/sync-wave: "0"
data:
{{- $files := .Files }}
{{- range $path, $_ :=  $files.Glob  "migrations/*.sql" }}
{{ base $path | indent 2 }}: |-
{{ $files.Get $path | indent 4 }}
{{- end }}
  atlas.sum: |-
{{ $files.Get "migrations/atlas.sum" | indent 4 }}