apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Chart.Name }}
spec:
  selector: 
    app: {{ .Chart.Name }}
  ports:
  - name: api
    port: 9000
    targetPort: 9000
