// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package pgdb

import (
	"database/sql"
)

type User struct {
	ID    string
	Name  string
	Email sql.NullString
	Title sql.NullString
	Foo   sql.NullString
}
